### PR TITLE
Gitlab ci support

### PR DESCRIPTION
**Pull request by melo**
Add support for gitlab-ci, consistent with codecov/codecov-bash#50.

### CODE REVIEW

**Comment by melo** [comment]
Not sure about the Shippable status... It seems to be a configuration issue, not a bug in the code.

The tests all pass locally with:

    carton install
    carton exec -- prove -lr

**Comment by pine** [comment]
Thank you PR!

>Not sure about the Shippable status... It seems to be a configuration issue, not a bug in the code.

No problem. Please ignore Sippable tests because Travis CI and AppVeyor statuses are green.

**Comment by melo** [comment]
Most excellent :)

**Comment by pine** [comment]
I'll plan to release this version soon. Please wait...

**Pull request merged**
