### PR TITLE
updated CI env

### PR DESCRIPTION
**Pull request by stevepeak**
> First Perl hack...:game_die: 

Updated some environment variables

### CODE REVIEW

**Comment by pine** [comment]
Perhaps it is typo. I'll fix.

**Comment by pine** [comment]
Thanks!

**Comment by stevepeak** [comment]
Sorry, that was my bad. Fixing now

**Comment by pine** [comment]
:+1: 

I should write document for codecov-perl developer...

**Comment by pine** [comment]
@stevepeak  I've just written Wiki how to execute and test now.
https://github.com/codecov/codecov-perl/wiki/Contributing

**Comment by stevepeak** [comment]
Very nice :+1:

**Pull request merged**
